apiVersion: v1
kind: Secret
metadata:
  name: color-secret
  namespace: color-app
type: Opaque
data:
  SECRET_KEY: bXktc2VjcmV0LXZhbHVlCg==

--- 
apiVersion: v1
kind: Pod
metadata:
  name: color-app
  namespace: color-app
  labels:
    app: color-app
    env: prod
    team: devops
spec:
  containers:
  - name: color-app-container
    image: 211125430491.dkr.ecr.us-east-1.amazonaws.com/color-app:v1.0
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: color-app-config
    - secretRef:
        name: color-secret